let DiagnosticTestsAndMonitoring = [
  "SPIROMETRY",
  "BLOOD GLUCOSE TEST",
  "CHOLESTEROL TEST",
  "ELECTROCARDIOGRAM",
  "MRI_SCAN",
  "CT_SCAN",
  "X_RAY",
  "ULTRASOUND",
  "COLONOSCOPY",
  "MAMMOGRAPHY",
  "PAP SMEAR",
  "PROSTATE SPECIFIC ANTIGEN TEST",
  "BONE DENSITY TEST",
  "THYROID FUNCTION TEST",
  "LIVER FUNCTION TEST",
  "KIDNEY FUNCTION TEST",
  "PULMONARY FUNCTION TEST",
  "BLOOD PRESSURE MEASUREMENT",
  "ALLERGY TEST",
  "GENETIC TESTING",
  "CANCER SCREENING",
  "IMMUNOLOGICAL TEST",
  "ENDOSCOPIC EXAMINATION",
  "AUDIOMETRY",
  "VISUAL ACUITY TEST",
  "OPHTHALMOSCOPY",
  "DERMATOLOGICAL EXAMINATION",
  "ELECTROENCEPHALOGRAM",
  "LUMBAR PUNCTURE",
  "BIOPSY",
];

let PreventionAndTherapies = [
  "DIET CONTROL",
  "REGULAR EXERCISE",
  "MEDICATION",
  "VACCINATION",
  "STRESS MANAGEMENT",
  "SMOKING CESSATION",
  "ALCOHOL MODERATION",
  "HYDRATION",
  "SLEEP HYGIENE",
  "WEIGHT MANAGEMENT",
  "SCREENING TESTS",
  "PHYSICAL THERAPY",
  "OCCUPATIONAL THERAPY",
  "COGNITIVE BEHAVIORAL THERAPY",
  "SURGERY",
  "RADIATION THERAPY",
  "CHEMOTHERAPY",
  "HORMONE THERAPY",
  "IMMUNOTHERAPY",
  "ANTIBIOTIC THERAPY",
];

let PotentialProblems = [
  "TUMOR",
  "CANCER",
  "DIABETES",
  "HEART DISEASE",
  "LIVER DISEASE",
  "KIDNEY DISEASE",
  "ASTHMA",
  "OBESITY",
  "HIGH CHOLESTEROL",
  "HIGH BLOOD PRESSURE",
  "HIGH BLOOD SUGAR",
  "HIGH BLOOD OXYGEN",
  "HIGH BLOOD GLUCOSE",
  "HIGH BODY TEMPERATURE",
  "HIGH BODY PRESSURE",
  "ARTHRITIS",
  "OSTEOPOROSIS",
  "DEPRESSION",
  "ANXIETY",
  "DEMENTIA",
  "ALZHEIMER",
  "THYROID DISORDER",
  "GASTROESOPHAGEAL REFLUX DISEASE",
  "PEPTIC ULCER DISEASE",
  "MIGRAINE",
  "CHRONIC KIDNEY DISEASE",
  "LIVER CIRRHOSIS",
  "SINUSITIS",
  "INFECTIOUS DISEASES",
  "CHRONIC FATIGUE SYNDROME",
  "IRRITABLE BOWEL SYNDROME",
  "ENDOMETRIOSIS",
  "FIBROMYALGIA",
  "PSORIASIS",
];

let Medications = [
  "PARACETAMOL",
  "IBUPROFEN",
  "ASPIRIN",
  "OMEPRAZOLE",
  "LISINOPRIL",
  "ATORVASTATIN",
  "METFORMIN",
  "AMLODIPINE",
  "SIMVASTATIN",
  "LEVOTHYROXINE",
  "LOSARTAN",
  "HYDROCHLOROTHIAZIDE",
  "GABAPENTIN",
  "METOPROLOL",
  "ARIPIPRAZOLE",
  "PREDNISONE",
  "SERTRALINE",
  "ALPRAZOLAM",
  "TRAMADOL",
  "CITALOPRAM",
  "DIAZEPAM",
  "WARFARIN",
  "FLUOXETINE",
  "AMOXICILLIN",
  "ESCITALOPRAM",
  "FUROSEMIDE",
  "AZITHROMYCIN",
  "ALBUTEROL",
  "PANTOPRAZOLE",
  "METRONIDAZOLE",
  "CARVEDILOL",
  "VENLAFAXINE",
  "LORAZEPAM",
  "FLUTICASONE",
  "TRAZODONE",
  "CEPHALEXIN",
  "CLONAZEPAM",
  "TAMSULOSIN",
  "CIPROFLOXACIN",
  "DULOXETINE",
  "BUPROPION",
  "MIRTAZAPINE",
  "NAPROXEN",
  "RISPERIDONE",
  "AMITRIPTYLINE",
  "DOXYCYCLINE",
  "CYCLOBENZAPRINE",
  "CELECOXIB",
  "HYDROXYZINE",
  "VALSARTAN",
  "QUETIAPINE",
  "PREGABALIN",
  "METFORMIN",
  "PREGABALIN",
  "TRAMADOL",
  "OXYCODONE",
  "MORPHINE",
  "FENTANYL",
  "METHADONE",
  "CODEINE",
  "HYDROMORPHONE",
  "BUPRENORPHINE",
  "NALOXONE",
  "ROPINIROLE",
  "MEMANTINE",
  "DONEPEZIL",
  "GALANTAMINE",
  "RIVASTIGMINE",
  "METHYLPHENIDATE",
  "ATOMOXETINE",
  "LISDEXAMFETAMINE",
  "DEXTROAMPHETAMINE",
  "MODAFINIL",
  "ARMODAFINIL",
  "PRAMIPEXOLE",
  "ROTIGOTINE",
  "BROMOCRIPTINE",
  "CARBIDOPA/LEVODOPA",
  "ENTACAPONE",
  "RASAGILINE",
  "SELEGILINE",
  "AMANTADINE",
  "APOMORPHINE",
  "TRIHEXYPHENIDYL",
  "BENZATROPINE",
  "PROCYCLIDINE",
  "BOTULINUM TOXIN",
  "CLONIDINE",
  "GUANFACINE",
  "NALTREXONE",
  "DISULFIRAM",
  "ACAMPROSATE",
  "NALMEFENE",
  "BUPRENORPHINE",
  "METHADONE",
  "NALOXONE",
  "NALTREXONE",
  "ACAMPROSATE",
  "DISULFIRAM",
  "TOPIRAMATE",
  "ARIPIPRAZOLE",
  "LAMOTRIGINE",
  "LURASIDONE",
  "OLANZAPINE",
  "QUETIAPINE",
  "RISPERIDONE",
  "ZIPRASIDONE",
  "CARIPRAZINE",
  "CHLORPROMAZINE",
  "FLUPHENAZINE",
  "HALOPERIDOL",
  "LOXAPINE",
  "PERPHENAZINE",
  "PIMOZIDE",
  "THIORIDAZINE",
  "THIOTHIXENE",
  "TRIFLUOPERAZINE",
  "AMISULPRIDE",
  "CLOZAPINE",
  "ILOPERIDONE",
  "LURASIDONE",
  "OLANZAPINE",
  "PALIPERIDONE",
  "RISPERIDONE",
  "QUETIAPINE",
  "ZIPRASIDONE",
  "ARIPIPRAZOLE",
  "BREXPIPRAZOLE",
  "CARIPRAZINE",
  "ARIPIPRAZOLE",
  "BREXPIPRAZOLE",
  "CARIPRAZINE",
  "DAPOXETINE",
  "CITALOPRAM",
  "ESCITALOPRAM",
  "FLUOXETINE",
  "FLUVOXAMINE",
  "PAROXETINE",
  "SERTRALINE",
  "VENLAFAXINE",
  "DULOXETINE",
  "DESVENLAFAXINE",
];

let test = {
  MOLD: {
    severity: "MILD",
    sideEffects: [
      "itching",
      "swelling",
      "redness",
      "wheals",
      "angioedema",
      "anaphylaxis",
    ],
  },
  POLLEN: {
    severity: "MODERATE",
    sideEffects: [
      "sneezing",
      "runny nose",
      "itchy eyes",
      "congestion",
      "coughing",
    ],
  },
  DUST: {
    severity: "MILD",
    sideEffects: [
      "sneezing",
      "coughing",
      "wheezing",
      "shortness of breath",
      "itchy or watery eyes",
    ],
  },
  "PET DANDER": {
    severity: "MILD",
    sideEffects: [
      "sneezing",
      "runny or stuffy nose",
      "itchy or watery eyes",
      "coughing",
      "wheezing",
    ],
  },
  "FOOD ALLERGIES": {
    severity: "VARIES",
    sideEffects: [
      "hives",
      "itching",
      "swelling",
      "abdominal pain",
      "diarrhea",
      "nausea",
      "vomiting",
    ],
  },
  "INSECT BITES/STINGS": {
    severity: "VARIES",
    sideEffects: [
      "itching",
      "swelling",
      "redness",
      "pain",
      "rash",
      "difficulty breathing",
      "dizziness",
      "nausea",
    ],
  },
  "MEDICATION ALLERGIES": {
    severity: "VARIES",
    sideEffects: [
      "rash",
      "hives",
      "itching",
      "swelling",
      "wheezing",
      "anaphylaxis",
    ],
  },
  LATEX: {
    severity: "VARIES",
    sideEffects: [
      "skin rash",
      "hives",
      "itching",
      "swelling",
      "runny nose",
      "sneezing",
      "coughing",
      "wheezing",
      "shortness of breath",
      "anaphylaxis",
    ],
  },
  "CHEMICAL ALLERGIES": {
    severity: "VARIES",
    sideEffects: [
      "skin irritation",
      "rash",
      "itching",
      "redness",
      "swelling",
      "burning sensation",
      "difficulty breathing",
      "wheezing",
      "coughing",
      "nausea",
      "headache",
    ],
  },
  "COSMETIC ALLERGIES": {
    severity: "VARIES",
    sideEffects: [
      "skin irritation",
      "rash",
      "itching",
      "redness",
      "swelling",
      "burning sensation",
      "bumps",
      "blistering",
      "peeling",
      "hives",
      "anaphylaxis",
    ],
  },
  "METAL ALLERGIES": {
    severity: "VARIES",
    sideEffects: [
      "skin rash",
      "itching",
      "redness",
      "swelling",
      "blisters",
      "oozing",
      "crusting",
      "burning sensation",
      "hives",
      "anaphylaxis",
    ],
  },
  "HAY FEVER": {
    severity: "MODERATE",
    sideEffects: [
      "sneezing",
      "runny or stuffy nose",
      "itchy or watery eyes",
      "coughing",
      "fatigue",
    ],
  },
  "SEASONAL ALLERGIES": {
    severity: "MODERATE",
    sideEffects: [
      "sneezing",
      "runny or stuffy nose",
      "itchy or watery eyes",
      "coughing",
      "fatigue",
    ],
  },
  "ENVIRONMENTAL ALLERGIES": {
    severity: "VARIES",
    sideEffects: [
      "sneezing",
      "runny or stuffy nose",
      "itchy or watery eyes",
      "coughing",
      "wheezing",
      "shortness of breath",
      "headache",
      "fatigue",
    ],
  },
  "ALLERGIC RHINITIS": {
    severity: "MODERATE",
    sideEffects: [
      "sneezing",
      "runny or stuffy nose",
      "itchy or watery eyes",
      "coughing",
      "fatigue",
    ],
  },
  ECZEMA: {
    severity: "MILD",
    sideEffects: [
      "itching",
      "redness",
      "dryness",
      "rash",
      "scaly or thickened skin",
      "crusting",
      "oozing",
      "bleeding",
    ],
  },
  "ASTHMA TRIGGERS": {
    severity: "VARIES",
    sideEffects: [
      "coughing",
      "wheezing",
      "shortness of breath",
      "chest tightness",
      "difficulty breathing",
    ],
  },
  "ALLERGIC CONJUNCTIVITIS": {
    severity: "MILD",
    sideEffects: [
      "itchy or watery eyes",
      "redness",
      "swelling",
      "burning sensation",
      "sensitivity to light",
    ],
  },
  HIVES: {
    severity: "MILD",
    sideEffects: ["itching", "redness", "swelling", "wheals", "angioedema"],
  },
  ANAPHYLAXIS: {
    severity: "SEVERE",
    sideEffects: [
      "difficulty breathing",
      "wheezing",
      "swelling",
      "rash",
      "hives",
      "nausea",
      "vomiting",
      "dizziness",
      "loss of consciousness",
    ],
  },
};

let Allergies = [
  "POLLEN",
  "DUST",
  "PET DANDER",
  "MOLD",
  "FOOD ALLERGIES",
  "INSECT BITES/STINGS",
  "MEDICATION ALLERGIES",
  "LATEX",
  "CHEMICAL ALLERGIES",
  "COSMETIC ALLERGIES",
  "METAL ALLERGIES",
  "HAY FEVER",
  "SEASONAL ALLERGIES",
  "ENVIRONMENTAL ALLERGIES",
  "ALLERGIC RHINITIS",
  "ECZEMA",
  "ASTHMA TRIGGERS",
  "ALLERGIC CONJUNCTIVITIS",
  "HIVES",
  "ANAPHYLAXIS",
];

export {
  PotentialProblems,
  PreventionAndTherapies,
  DiagnosticTestsAndMonitoring,
  Medications,
  Allergies,
  test,
};
